// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skoquwtexkosschxekmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrb3F1d3RleGtvc3NjaHhla214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODIyMDEsImV4cCI6MjA2MzY1ODIwMX0.nMC2C0-JSC70_ytwiBWkSfj7jVwpDaYx6tL8UCWG9Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);